# Generated by Django 4.2.27 on 2026-09-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0026_alertnotificationdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="monitor_objects",
            field=models.JSONField(blank=True, default=list, help_text="关联监控对象身份快照"),
        ),
        migrations.AddField(
            model_name="event",
            name="cmdb_id",
            field=models.CharField(blank=True, help_text="CMDB实例ID快照", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="monitor_id",
            field=models.CharField(blank=True, help_text="监控实例ID快照", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="resource_type",
            field=models.CharField(blank=True, help_text="资源类型", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="resource_id",
            field=models.CharField(blank=True, db_index=True, help_text="资源唯一ID", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="resource_type",
            field=models.CharField(blank=True, help_text="资源类型", max_length=100, null=True),
        ),
    ]
