"""
Vastbase G100（海量数据）B 兼容模式补丁集合。

背景
====
客户的 Vastbase G100 V3.0.9 实例：openGauss 内核、PostgreSQL 9.2.4 血统、走 PG 线协议，
建库时使用 ``DBCOMPATIBILITY='B'``（MySQL 兼容模式）。BK-Lite 通过 ``DB_ENGINE=postgresql``
（Django 原生 postgresql 后端）连接它，额外设置 ``PG_COMPAT=vastbase`` 启用本模块。

与 [[kingbase]] 的关键差异
==========================
同为 MySQL 兼容模式，但 Vastbase 的 B 模式**保留了 PG 语义**，实测确认：

* ``||`` 仍是字符串拼接（返回 text），**不需要** kingbase 那套 concat 改写；
* 双引号仍是标识符定界符，保留字列名（如 ``"select"``）可正常读写；
* jsonb 类型、``->`` ``->>`` ``@>`` ``#>>`` ``?`` 操作符、``jsonb_agg`` 及 jsonb 上的
  GIN 索引全部可用——926 处 JSONField 无需替代方案；
* 正则 ``~`` / ``~*``、``E'...'`` 转义串、``ILIKE``、``DISTINCT ON``、
  ``varchar_pattern_ops`` 索引均可用；
* timestamptz 语义正确（同一时刻的不同写法 epoch 一致）。

因此本模块只处理 7 类真实不兼容点，比 kingbase 补丁更短。

补丁清单
========
1. **版本门**（migrate 阻断）：Vastbase 上报 ``server_version = 9.2.4``，而 Django 4.2 的
   ``postgresql`` 后端设 ``minimum_database_version = (12,)``，连接建立即被拒。覆盖为 ``None``
   跳过该检查。

2. **introspection PG12+ 语法**（migrate 阻断）：Django 的 introspection SQL 用了三处
   Vastbase 不支持的写法，改写为 9.2 时代的等价形式（详见 ``_SQL_REWRITES``）。

3. **IDENTITY 退化 serial**（migrate 阻断）：``GENERATED BY DEFAULT AS IDENTITY`` 语法不支持，
   AutoField 系列退回 ``serial`` / ``bigserial`` / ``smallserial``。

4. **ON CONFLICT 无 target**（运行期阻断）：B 模式只认带 target 的 ``ON CONFLICT``，
   报 ``Conflict without target is not yet supported``。而 Django 的 ``ignore_conflicts=True``
   生成的正是无 target 形式，server 内 60 余处依赖它。改写为 B 模式原生的
   ``ON DUPLICATE KEY UPDATE <col> = <col>``——它同样吞掉**任意**唯一约束的冲突，
   语义与 ``ignore_conflicts`` 等价；而「自动补一个 target」的做法在多唯一约束的表上
   会漏掉其它约束的冲突，实测会抛 IntegrityError，故不采用。

5. **sequence_reset_sql**：B 模式把 ``serial`` 实现为 auto_increment 列，其 owned sequence
   拒绝 ``setval``（``cannot change sequence owned by auto_increment column``）。
   置空该 SQL——auto_increment 自身维护计数，无需重置。

6. **naive datetime（psycopg2 路径）**：服务端输出 timestamptz **不带时区偏移**，psycopg2
   解析宽松，返回 naive datetime。项目 ``USE_TZ=True``，Django 拿到 naive 值会触发
   RuntimeWarning 且时间比较可能出偏差 → 在 ``get_db_converters`` 注册转换器补成 UTC aware。

7. **timestamptz 解析失败（psycopg3 路径）**：psycopg3 的 ``TimestamptzLoader`` 要求数据带时区
   偏移，缺失时回退连接时区；而 Django 连接上该时区为 unknown，于是直接抛
   ``DataError: can't parse timestamp ... (unknown)``。实测 migrate 行进到 apm.0009 的
   RunPython 读数据时必然触发。→ 包装 loader，补上会话偏移后重试。
   偏移值由 ``connection_created`` 时**实测**（``EXTRACT(TIMEZONE FROM now())``），
   不硬编码 ``+00``：若会话时区并非 UTC，硬编码会静默引入整点偏差，比报错更难发现。

   注意 6 与 7 覆盖的是**两种驱动**：pyproject 锁定 psycopg2-binary，但运行镜像内装有
   psycopg3（opspilot extra 经 langchain-postgres 带入），Django 4.2 会优先使用 psycopg3。
   两条补丁必须同时存在。

已知未覆盖
==========
* ``DatabaseSchemaEditor.sql_add_identity`` / ``sql_drop_indentity`` 未改写。它们仅在
  「把已有普通字段 AlterField 成 AutoField」时触发，当前 migration 中不存在该操作；
  若将来出现会直接报语法错（不会静默写坏数据），届时再补。
* ``update_conflicts=True`` 路径保持 Django 原生的 ``ON CONFLICT(...) DO UPDATE``——
  实测该形式在 B 模式下可用，且 server 生产代码中无任何真实使用方。
* 本模块依赖 Django 4.2 ``QuerySet._batched_insert`` 中
  ``if bulk_return and on_conflict is None`` 这一分支：``on_conflict`` 非 None 时不生成
  ``RETURNING``。这很重要——B 模式下 ``RETURNING`` 与 ``ON DUPLICATE KEY`` 不能共存
  （``RETURNING clause is not yet supported within INSERT ON DUPLICATE KEY statement``）。
  升级 Django 时若该分支变动，``bulk_create(ignore_conflicts=True)`` 会立刻报错暴露。

启用方式
========
保持 ``DB_ENGINE=postgresql``，额外设置 ``PG_COMPAT=vastbase``。
在 ``config/components/database.py`` 的 settings 加载阶段调用 ``apply_early_patches()``，
与 kingbase 同一注入时机，确保早于 migrate / introspection。

部署前置
========
建库必须 ``DBCOMPATIBILITY='B'`` 或 ``'PG'``（本模块针对 B 模式验证；PG 模式下补丁 4、5
不会被触发，其余仍适用）。openGauss 系默认 ``password_encryption_type`` 需允许 md5，
否则社区 psycopg2/psycopg3 无法完成握手。
"""

import datetime
import re

from django.conf import settings
from django.utils import timezone

from apps.core.logger import logger

# 标记补丁是否已应用，避免重复
_patches_applied = False


# ============================================================
# introspection SQL 改写规则
# ============================================================
# 采用**正则重写**而非逐字复制 Django 源码：Django 4.2.x 的补丁版本间
# introspection SQL 的空白与换行会变动，逐字镜像（kingbase 的做法）每次升级都要重新同步，
# 而按语法片段重写只依赖稳定的 SQL 结构。
#
# 每条规则都经真实实例验证等价（样本表含 PK / 单列 unique / 复合 unique / FK / DESC 复合索引）。
_SQL_REWRITES = (
    # 1) pg_class.relispartition 是 PG 10+ 列，Vastbase 没有；openGauss 用 parttype，
    #    非分区表取 'n'（实例上 1106 个对象全为 'n'）。
    (
        "relispartition",
        re.compile(r"c\.relispartition"),
        "(c.parttype <> 'n')",
    ),
    # 2) WITH ORDINALITY 是 PG 9.4+ 语法。conkey 是 smallint[]（1-based），
    #    generate_subscripts 给出与数组下标严格对应的序号。
    #    arridx 在 Django 中仅用于 ORDER BY，与起始值无关。
    (
        "conkey_ordinality",
        re.compile(r"unnest\(c\.conkey\)\s+WITH\s+ORDINALITY\s+cols\(\s*colid\s*,\s*arridx\s*\)"),
        "(SELECT unnest(c.conkey) AS colid, generate_subscripts(c.conkey, 1) AS arridx) cols",
    ),
    # 3) 多参数 unnest(a, b) 是 PG 9.4+ 特性，Vastbase 报
    #    "function unnest(integer[], integer[]) does not exist"；LATERAL 亦不可用（9.3+）。
    #    退回 9.2 时代写法：target list 中并排放多个 SRF 并行展开。
    #    indkey/indoption 长度恒等，不会触发 SRF 长度不齐时的 LCM 循环行为。
    #    注意 indkey 是 int2vector（0-based），故 arridx 从 0 起——Django 仅用它
    #    ``array_agg(... ORDER BY arridx)`` 排序，起始值无影响。
    (
        "indkey_ordinality",
        re.compile(
            r"SELECT\s+\*\s+FROM\s+pg_index\s+i\s*,\s*"
            r"unnest\(\s*i\.indkey\s*,\s*i\.indoption\s*\)\s+"
            r"WITH\s+ORDINALITY\s+koi\(\s*key\s*,\s*option\s*,\s*arridx\s*\)"
        ),
        "SELECT i.*, unnest(i.indkey) AS key, unnest(i.indoption) AS option, " "generate_subscripts(i.indkey, 1) AS arridx FROM pg_index i",
    ),
)


def rewrite_introspection_sql(sql):
    """把 Django introspection SQL 中的 PG12+ 写法改写为 Vastbase 可执行的等价形式。

    未命中任何规则时原样返回，因此对非 introspection 语句无副作用。
    """
    for _name, pattern, replacement in _SQL_REWRITES:
        sql = pattern.sub(replacement, sql)
    return sql


class _RewritingCursor:
    """包装 cursor，在 execute 时改写 introspection SQL。

    只拦截 execute，其余属性透传给真实 cursor，避免复制 Django 的 introspection 实现。
    """

    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, sql, params=None):
        return self._cursor.execute(rewrite_introspection_sql(sql), params)

    def __getattr__(self, name):
        return getattr(self._cursor, name)

    def __iter__(self):
        return iter(self._cursor)


def apply_early_patches():
    """应用 Vastbase B 兼容模式补丁。

    在 ``config/components/database.py`` 中、当 ``DB_ENGINE=postgresql`` 且
    ``PG_COMPAT=vastbase`` 时调用。幂等：重复调用只生效一次。
    """
    global _patches_applied
    if _patches_applied:
        return
    _patches_applied = True

    _patch_minimum_database_version()
    _patch_introspection_pg12_syntax()
    _patch_identity_to_serial()
    _patch_on_conflict_ignore()
    _patch_sequence_reset_sql()
    _patch_naive_datetime_converter()
    _patch_psycopg3_timestamptz_missing_tz()

    logger.info(
        "Vastbase B-mode patches applied "
        "(version gate + introspection + serial + on-conflict + sequence reset + "
        "naive datetime + psycopg3 timestamptz)"
    )


def _patch_minimum_database_version():
    """跳过 Django 4.2 的 PostgreSQL >= 12 硬检查。

    Vastbase 上报 ``server_version = 9.2.4``（openGauss 沿用的 PG 血统版本号），
    与实际功能集无关；不跳过则 ``BaseDatabaseWrapper.check_database_version_supported``
    在建连时直接抛 NotSupportedError。
    """
    from django.db.backends.postgresql.features import DatabaseFeatures

    DatabaseFeatures.minimum_database_version = None


def _patch_introspection_pg12_syntax():
    """改写 introspection 中 Vastbase 不支持的 PG12+ 语法（migrate 阻断点）。

    包装 ``get_table_list`` 与 ``get_constraints``，向原实现传入会改写 SQL 的代理 cursor。
    """
    from django.db.backends.postgresql.introspection import DatabaseIntrospection

    original_get_table_list = DatabaseIntrospection.get_table_list
    original_get_constraints = DatabaseIntrospection.get_constraints

    def get_table_list(self, cursor):
        return original_get_table_list(self, _RewritingCursor(cursor))

    def get_constraints(self, cursor, table_name):
        return original_get_constraints(self, _RewritingCursor(cursor), table_name)

    DatabaseIntrospection.get_table_list = get_table_list
    DatabaseIntrospection.get_constraints = get_constraints


def _patch_identity_to_serial():
    """AutoField 系列由 IDENTITY 退化为 serial。

    Vastbase 不支持 ``GENERATED BY DEFAULT AS IDENTITY``（报 ``syntax error at or near "BY"``），
    ``bigserial`` 等则可正常建表。
    """
    from django.db.backends.postgresql.base import DatabaseWrapper

    DatabaseWrapper.data_types = {
        **DatabaseWrapper.data_types,
        "AutoField": "serial",
        "BigAutoField": "bigserial",
        "SmallAutoField": "smallserial",
    }
    # serial 已隐含序列与默认值，不能再追加 IDENTITY 后缀
    DatabaseWrapper.data_types_suffix = {}


def _patch_on_conflict_ignore():
    """``ON CONFLICT DO NOTHING``（无 target）改写为 ``ON DUPLICATE KEY UPDATE <col> = <col>``。

    仅改写 IGNORE 分支；UPDATE 分支的 ``ON CONFLICT(...) DO UPDATE`` 在 B 模式下原生可用，
    保持 Django 实现不变。
    """
    from django.db.backends.postgresql.operations import DatabaseOperations
    from django.db.models.constants import OnConflict

    original = DatabaseOperations.on_conflict_suffix_sql

    def on_conflict_suffix_sql(self, fields, on_conflict, update_fields, unique_fields):
        if on_conflict == OnConflict.IGNORE and fields:
            # 自赋值实现「命中任意唯一键则跳过、不改动任何值」，等价于 ignore_conflicts
            column = self.quote_name(fields[0].column)
            return "ON DUPLICATE KEY UPDATE {} = {}".format(column, column)
        return original(self, fields, on_conflict, update_fields, unique_fields)

    DatabaseOperations.on_conflict_suffix_sql = on_conflict_suffix_sql


def _patch_sequence_reset_sql():
    """置空序列重置 SQL。

    B 模式下 serial 落地为 auto_increment 列，其 owned sequence 拒绝 ``setval``：
    ``cannot change sequence owned by auto_increment column``。
    auto_increment 自行维护计数，无需外部重置；返回空列表让 loaddata / sqlsequencereset
    成为 no-op，而不是整条命令失败。
    """
    from django.db.backends.postgresql.operations import DatabaseOperations

    def sequence_reset_sql(self, style, model_list):
        return []

    def sequence_reset_by_name_sql(self, style, sequences):
        return []

    DatabaseOperations.sequence_reset_sql = sequence_reset_sql
    DatabaseOperations.sequence_reset_by_name_sql = sequence_reset_by_name_sql


def _convert_naive_datetime(value, expression, connection):
    """把服务端返回的 naive datetime 补成 UTC aware。

    连接会话时区由 Django 固定为 UTC，故裸值即 UTC 时刻。
    """
    if value is not None and timezone.is_naive(value):
        return value.replace(tzinfo=datetime.timezone.utc)
    return value


def _patch_naive_datetime_converter():
    """为 DateTimeField 注册 naive -> UTC aware 转换器。

    Vastbase 输出 timestamptz 不带时区偏移，psycopg2 据此返回 naive datetime；
    ``USE_TZ=True`` 下 Django 期望 aware 值。
    """
    from django.db.backends.postgresql.operations import DatabaseOperations

    original = DatabaseOperations.get_db_converters

    def get_db_converters(self, expression):
        converters = original(self, expression)
        if settings.USE_TZ and expression.output_field.get_internal_type() == "DateTimeField":
            converters.append(_convert_naive_datetime)
        return converters

    DatabaseOperations.get_db_converters = get_db_converters


# ============================================================
# psycopg3：容忍不带时区偏移的 timestamptz
# ============================================================
# 连接会话相对 UTC 的偏移，由 connection_created 时实测填入（形如 b"+00:00"）。
# 默认值对应 Django 固定的 SET TIME ZONE 'UTC'；实测失败时退回该默认值。
_SESSION_UTC_OFFSET = b"+00:00"
_SESSION_OFFSET_LOGGED = False


def _capture_session_utc_offset(sender, connection, **kwargs):
    """连接建立后实测一次会话时区偏移，供 TimestamptzLoader 兜底解析使用。

    ``connection_created`` 在 ``init_connection_state()`` **之后**触发，此时 Django 的
    ``SET TIME ZONE`` 已生效，测到的就是后续查询实际使用的会话时区。

    刻意用 ``EXTRACT(TIMEZONE FROM now())`` 取偏移**秒数**而不是读 timestamptz 值——
    前者返回 numeric，不经过 TimestamptzLoader，不会触发正要修复的那个解析错误。
    """
    global _SESSION_UTC_OFFSET, _SESSION_OFFSET_LOGGED

    if connection.vendor != "postgresql":
        return
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT EXTRACT(TIMEZONE FROM now())")
            seconds = int(cursor.fetchone()[0])
    except Exception:
        # 取不到就沿用默认 +00:00；这里不能让诊断动作阻断建连
        logger.warning(
            "Vastbase: failed to detect session UTC offset, assuming %s",
            _SESSION_UTC_OFFSET.decode(),
        )
        return

    sign = "+" if seconds >= 0 else "-"
    seconds = abs(seconds)
    offset = ("%s%02d:%02d" % (sign, seconds // 3600, (seconds % 3600) // 60)).encode()
    changed = offset != _SESSION_UTC_OFFSET
    _SESSION_UTC_OFFSET = offset

    if changed or not _SESSION_OFFSET_LOGGED:
        _SESSION_OFFSET_LOGGED = True
        logger.info(
            "Vastbase: session UTC offset detected as %s (used to parse timestamptz without offset)",
            offset.decode(),
        )


def _patch_psycopg3_timestamptz_missing_tz():
    """psycopg3：为不带时区偏移的 timestamptz 补上会话偏移后重试解析。

    Vastbase 输出 timestamptz 不带偏移（如 ``2026-09-07 04:21:24.701866``），而 psycopg3 的
    ``TimestamptzLoader`` 要求带偏移，拿不到时回退连接时区——若连接时区未知则直接抛
    ``DataError: can't parse timestamp ... (unknown)``。实测在容器内的 Django 连接上必然触发，
    表现为 migrate 中途 RunPython 读数据即失败。

    psycopg2 解析更宽松，返回 naive datetime，由 ``_patch_naive_datetime_converter`` 处理；
    两条补丁互补，分别覆盖两种驱动。

    与 [[kingbase]] 同类补丁的差异：不硬编码 ``+00``，而使用 ``_capture_session_utc_offset``
    实测的会话偏移。若会话时区并非 UTC，硬编码会静默引入整点偏差——比报错更难发现。

    注意：``TimestamptzLoader`` 是进程级全局，多个不同时区的连接共存时只会使用最后一次
    实测到的偏移。本项目单库单连接配置，且 Django 统一 ``SET TIME ZONE 'UTC'``，不构成问题。
    """
    try:
        from psycopg.errors import DataError
        from psycopg.types.datetime import TimestamptzLoader
    except ImportError:
        # 纯 psycopg2 环境不需要此补丁
        logger.info("Vastbase: psycopg(v3) not installed, timestamptz loader patch skipped")
        return

    from django.db.backends.signals import connection_created

    connection_created.connect(_capture_session_utc_offset, dispatch_uid="vastbase_session_utc_offset")

    original_load = TimestamptzLoader.load

    def patched_load(self, data):
        try:
            return original_load(self, data)
        except DataError:
            if data is None:
                raise
            # 补上实测的会话偏移后重试；仍失败则抛出该次错误，不掩盖真正的异常
            return original_load(self, bytes(data) + _SESSION_UTC_OFFSET)

    TimestamptzLoader.load = patched_load
