# Generated by Django 4.2.27 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mlops", "0050_externalresourcecleanupintent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalresourcecleanupintent",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("mlflow_experiment_model", "MLflow experiment and model"),
                    ("minio_object", "MinIO object"),
                    ("webhook_container", "Webhook container"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
