[program:workflow_orchestration_worker]
command=python manage.py run_workflow_worker
directory=%(ENV_PROJECT_DIR)s
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
priority=20

[program:workflow_orchestration_trigger_scheduler]
command=python manage.py run_workflow_trigger_scheduler --interval 15
directory=%(ENV_PROJECT_DIR)s
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
priority=20

[program:workflow_orchestration_artifact_cleanup]
command=python manage.py run_workflow_artifact_cleanup_scheduler --interval 3600
directory=%(ENV_PROJECT_DIR)s
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
priority=20
