"""监控中心企业许可计费对象目录。

按监控对象名称白名单计数；未列出的对象默认不计费。
Host Remote / Windows WMI 是 Host 实例上的采集插件，不单独占许可。
腾讯云复合对象里的 TCP 是云 API 连接入口，不计费。
插件对象名是 Minio，不是 DEFAULT_OBJ_ORDER 里的 MinIO。
"""

MONITOR_LICENSE_OBJECT_NAMES = frozenset(
    {
        "Host",
        "Hardware Server",
        "Mysql",
        "Postgres",
        "Redis",
        "MongoDB",
        "MSSQL",
        "ElasticSearch",
        "InfluxDB",
        "Oracle",
        "DB2",
        "Dameng",
        "GBase8a",
        "Greenplum",
        "HANA",
        "IRIS",
        "KingBase",
        "OceanBase",
        "OpenGauss",
        "PolarDB PG",
        "Sybase",
        "TiDB",
        "TongRDS",
        "VastBase",
        "Kafka",
        "ActiveMQ",
        "RabbitMQ",
        "Zookeeper",
        "Etcd",
        "Consul",
        "Nginx",
        "Apache",
        "Tomcat",
        "Haproxy",
        "Minio",
        "JVM",
        "Active Directory",
        "Exchange",
        "BES",
        "IBMMQ",
        "JBoss",
        "Jetty",
        "Nacos",
        "TongLINKQ-D",
        "TongLink",
        "TongLinkQ",
        "TongWeb",
        "WebLogic",
        "WebSphere",
        "Docker",
        "Node",
        "K3SNode",
        "ESXI",
        "VM",
        "CVM",
        "ECS",
        "CNwareHost",
        "CNwareVM",
        "SangforSCPHost",
        "SangforSCPVM",
        "Storage",
        "Switch",
        "Router",
        "Firewall",
        "Loadbalance",
        "Access",
        "Wireless",
        "Transmission",
        "VoiceGateway",
        "ConsoleServer",
        "NetworkService",
        "Ping",
        "TCPPort",
        "Website",
    }
)
