# Generated by Django 4.2.27 on 2026-09-03 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0052_operation_event_context_change_record_attribute_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortFingerprint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                (
                    "port",
                    models.PositiveIntegerField(
                        help_text="TCP 端口", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]
                    ),
                ),
                ("protocol", models.CharField(default="tcp", help_text="协议", max_length=16)),
                ("target_type", models.CharField(help_text="CMDB 模型 ID", max_length=128)),
                ("built_in", models.BooleanField(default=False, verbose_name="是否内置")),
            ],
            options={
                "verbose_name": "端口指纹",
                "verbose_name_plural": "端口指纹",
                "unique_together": {("port", "target_type")},
            },
        ),
    ]
