# Generated by Django 4.2.27 on 2026-09-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012 - Django migration contract.
        ("cmdb", "0053_portfingerprint"),
    ]

    operations = [  # noqa: RUF012 - Django migration contract.
        migrations.CreateModel(
            name="FirstCollectionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("fingerprint", models.CharField(max_length=64)),
                ("task_revision", models.DateTimeField()),
                ("reason", models.CharField(default="create", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting_config", "等待配置"),
                            ("pending", "待触发"),
                            ("running", "触发中"),
                            ("retry_wait", "等待重试"),
                            ("accepted", "已接纳"),
                            ("partial", "部分接纳"),
                            ("failed", "触发失败"),
                            ("skipped", "已跳过"),
                        ],
                        default="waiting_config",
                        max_length=32,
                    ),
                ),
                ("config_attempt", models.PositiveSmallIntegerField(default=0)),
                ("dispatch_attempt", models.PositiveSmallIntegerField(default=0)),
                ("attempt", models.PositiveSmallIntegerField(default=0)),
                ("claim_token", models.CharField(blank=True, default="", max_length=64)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("channel_results", models.JSONField(default=dict)),
                ("failed_stage", models.CharField(blank=True, default="", max_length=64)),
                ("error_type", models.CharField(blank=True, default="", max_length=128)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collect_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first_collection_runs",
                        to="cmdb.collectmodels",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["status", "updated_at"], name="cmdb_first_collect_status_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="firstcollectionrun",
            constraint=models.UniqueConstraint(
                fields=("collect_task", "fingerprint", "task_revision"),
                name="cmdb_first_collect_task_revision_uniq",
            ),
        ),
    ]
