# Generated by Django 4.2.27 on 2026-09-21 09:02

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0049_credential_vault"),
        ("cmdb", "0056_scan_execution_schedule_family_run_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="CmdbTransferGuard",
            fields=[
                ("key", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("cursor", models.CharField(default="", max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="CmdbTransferTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=8)),
                ("model_id", models.CharField(max_length=128)),
                ("model_name", models.CharField(default="", max_length=128)),
                ("team_id", models.IntegerField()),
                ("include_children", models.BooleanField(default=False)),
                ("params", models.JSONField(default=dict)),
                ("authorization", models.JSONField(default=dict)),
                ("schema_hash", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("status", models.CharField(default="queued", max_length=24)),
                ("phase", models.CharField(default="queued", max_length=32)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("total_rows", models.PositiveIntegerField(null=True)),
                ("summary", models.JSONField(default=dict)),
                ("error_code", models.CharField(default="", max_length=64)),
                ("message", models.CharField(default="", max_length=512)),
                ("source_key", models.CharField(default="", max_length=512)),
                ("source_hash", models.CharField(default="", max_length=64)),
                ("filename", models.CharField(default="", max_length=255)),
                ("artifacts", models.JSONField(default=dict)),
                ("execution_token", models.CharField(default="", max_length=32)),
                ("holds_slot", models.BooleanField(db_index=True, default=False)),
                ("lease_expires_at", models.DateTimeField(null=True)),
                ("deadline_at", models.DateTimeField(null=True)),
                ("dispatched_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("delete_pending", models.BooleanField(default=False)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="system_mgmt.user")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["owner", "created_at"], name="cmdb_transfer_owner_date"),
                    models.Index(fields=["status", "lease_expires_at"], name="cmdb_transfer_state_lease"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="cmdbtransfertask",
            constraint=models.UniqueConstraint(fields=("owner", "idempotency_key"), name="cmdb_transfer_request_key"),
        ),
    ]
