# Generated by Django 4.2.27 on 2026-09-07 07:17

import django.utils.timezone
from django.db import migrations, models

import apps.rum.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RumAlertEvent",
            fields=[
                ("id", models.CharField(default=apps.rum.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("policy_id", models.CharField(db_index=True, max_length=36)),
                ("status", models.CharField(db_index=True, max_length=32)),
                ("severity", models.CharField(blank=True, default="", max_length=32)),
                ("metric_value", models.FloatField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("fired_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "rum_alert_events",
            },
        ),
        migrations.CreateModel(
            name="RumAlertPolicy",
            fields=[
                ("id", models.CharField(default=apps.rum.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("application", models.CharField(db_index=True, max_length=128)),
                ("metric", models.CharField(max_length=64)),
                ("severity", models.CharField(default="critical", max_length=32)),
                ("comparator", models.CharField(default=">", max_length=8)),
                ("warn_threshold", models.FloatField(default=0)),
                ("critical_threshold", models.FloatField(default=0)),
                ("for_duration_sec", models.IntegerField(default=0)),
                ("no_data", models.BooleanField(default=False)),
                ("renotify_minutes", models.IntegerField(blank=True, null=True)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("signal", models.CharField(blank=True, default="", max_length=64)),
                ("notify_channels", models.JSONField(default=list)),
                ("pending_since", models.DateTimeField(blank=True, null=True)),
                ("recovering_since", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rum_alert_policies",
            },
        ),
        migrations.CreateModel(
            name="RumEraseJob",
            fields=[
                ("id", models.CharField(default=apps.rum.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("application", models.CharField(db_index=True, max_length=128)),
                ("end_user_id", models.CharField(db_index=True, max_length=256)),
                ("status", models.CharField(db_index=True, default="submitted", max_length=32)),
                ("requested_by", models.CharField(blank=True, default="", max_length=128)),
                ("result_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rum_erase_jobs",
            },
        ),
        migrations.CreateModel(
            name="RumFunnel",
            fields=[
                ("id", models.CharField(default=apps.rum.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("steps", models.JSONField(default=list)),
                ("application", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("default_preset", models.CharField(blank=True, default="", max_length=64)),
                ("created_by", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rum_funnels",
            },
        ),
        migrations.CreateModel(
            name="RumIssue",
            fields=[
                ("id", models.CharField(default=apps.rum.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("fingerprint", models.CharField(max_length=128, unique=True)),
                ("status", models.CharField(default="open", max_length=32)),
                ("note", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_version", models.CharField(blank=True, default="", max_length=128)),
                ("ignored_until", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rum_issues",
            },
        ),
        migrations.CreateModel(
            name="RumReleaseBaseline",
            fields=[
                ("id", models.CharField(default=apps.rum.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("application", models.CharField(max_length=128, unique=True)),
                ("baseline_release", models.CharField(max_length=128)),
                ("created_by", models.CharField(blank=True, default="", max_length=128)),
                ("updated_by", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rum_release_baselines",
            },
        ),
        migrations.CreateModel(
            name="RumSourcemapCredential",
            fields=[
                ("application", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("token_digest", models.CharField(max_length=128)),
                ("created_by", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rum_sourcemap_credentials",
            },
        ),
        migrations.CreateModel(
            name="RumSourcemap",
            fields=[
                ("id", models.CharField(default=apps.rum.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("application", models.CharField(db_index=True, max_length=128)),
                ("release", models.CharField(db_index=True, max_length=128)),
                ("file_name", models.CharField(max_length=512)),
                ("content", models.BinaryField()),
                ("created_by", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "rum_sourcemaps",
                "indexes": [models.Index(fields=["application", "release"], name="rum_sm_app_release")],
            },
        ),
        migrations.CreateModel(
            name="RumSavedView",
            fields=[
                ("id", models.CharField(default=apps.rum.models.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("screen", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("context_json", models.TextField(blank=True, default="")),
                ("shared", models.BooleanField(db_index=True, default=False)),
                ("owner", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rum_saved_views",
                "indexes": [models.Index(fields=["screen", "owner"], name="rum_sv_screen_owner")],
            },
        ),
    ]
