# Generated by Django 4.2.27 on 2026-09-02 02:42

from django.db import migrations, models

import apps.core.mixinx


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0048_uploaded_provider_pack"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=128)),
                ("credential_type", models.CharField(db_index=True, max_length=64)),
                ("username", models.CharField(blank=True, default="", max_length=256)),
                ("payload", models.JSONField(default=dict)),
                ("team", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "连接凭据",
                "verbose_name_plural": "连接凭据",
                "ordering": ("-id",),
            },
            bases=(models.Model, apps.core.mixinx.EncryptMixin),
        ),
    ]
