# Generated by Django 4.2.27 on 2026-09-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_mgmt', '0048_uploaded_provider_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_builtin', models.BooleanField(default=False)),
                ('categories', models.JSONField(default=list)),
                ('fields', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Maintainer Fields',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('credential_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('group_id', models.PositiveIntegerField(db_index=True)),
                ('disabled', models.BooleanField(default=False)),
                ('fields', models.JSONField(default=dict)),
                ('type', models.ForeignKey(db_column='type_key', on_delete=django.db.models.deletion.PROTECT, to='system_mgmt.credentialtype', to_field='key')),
            ],
            options={
                'verbose_name': 'Maintainer Fields',
                'abstract': False,
            },
        ),
    ]
