# Generated by Django 4.2.27 on 2026-09-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_mgmt', '0050_systemapitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAPICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('source_ip', models.GenericIPAddressField(verbose_name='Source IP')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Username')),
                ('credential_type', models.CharField(blank=True, choices=[('', ''), ('api_token', 'API Token'), ('system_token', 'System Token')], default='', max_length=16, verbose_name='Credential Type')),
                ('token_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Token ID')),
                ('token_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Token Name')),
                ('system_id', models.CharField(blank=True, default='', max_length=32, verbose_name='System ID')),
                ('team_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Team ID')),
                ('api_kind', models.CharField(blank=True, choices=[('', ''), ('internal', 'Internal'), ('external', 'External')], default='', max_length=16, verbose_name='API Kind')),
                ('method', models.CharField(blank=True, default='', max_length=10, verbose_name='Method')),
                ('path', models.CharField(blank=True, default='', max_length=512, verbose_name='Path')),
                ('http_status', models.PositiveSmallIntegerField(verbose_name='HTTP Status')),
                ('error_code', models.CharField(blank=True, default='', max_length=32, verbose_name='Error Code')),
            ],
            options={
                'verbose_name': 'OpenAPI Call Log',
                'verbose_name_plural': 'OpenAPI Call Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', '-created_at'], name='system_mgmt_usernam_8564b6_idx'), models.Index(fields=['credential_type', 'token_id', '-created_at'], name='system_mgmt_credent_797e89_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='openapicalllog',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credential_type', 'system_token'), models.Q(('system_id', ''), _negated=True)), models.Q(models.Q(('credential_type', 'system_token'), _negated=True), ('system_id', '')), _connector='OR'), name='openapi_call_system_id_ck'),
        ),
    ]
