# Generated by Django 4.2.27 on 2026-09-24 03:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AtomConfigTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("organization_id", models.PositiveBigIntegerField(db_index=True)),
                ("atom_key", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=120)),
                ("parameters", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "workflow_orchestration_atom_config_template",
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AtomDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("key", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("category", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("driver", models.CharField(default="LOCAL", max_length=32)),
                ("built_in", models.BooleanField(default=True)),
                ("team", models.JSONField(default=list)),
                ("input_schema", models.JSONField(default=dict)),
                ("output_schema", models.JSONField(default=dict)),
                ("ui_schema", models.JSONField(default=dict)),
                ("execution_config", models.JSONField(default=dict)),
                ("default_timeout_seconds", models.PositiveIntegerField(default=600)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("retry_delay_seconds", models.PositiveIntegerField(default=5)),
                ("idempotent", models.BooleanField(default=False)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=200)),
                ("error_types", models.JSONField(default=list)),
                ("safety_level", models.CharField(default="READ_ONLY", max_length=16)),
                ("required_permissions", models.JSONField(default=list)),
                ("resource_scope", models.CharField(default="ORGANIZATION", max_length=32)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("SYSTEM", "系统节点"), ("PLATFORM", "平台能力"), ("PACKAGE", "研发标准包")], db_index=True, default="PLATFORM", max_length=16
                    ),
                ),
            ],
            options={
                "db_table": "workflow_orchestration_atom_definition",
                "ordering": ("category", "name", "key"),
            },
        ),
        migrations.CreateModel(
            name="AtomExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("conductor_task_id", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("task_reference", models.CharField(db_index=True, max_length=100)),
                ("atom_key", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "等待执行"), ("RUNNING", "执行中"), ("COMPLETED", "成功"), ("FAILED", "失败"), ("SKIPPED", "已跳过")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("job_task_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("input", models.JSONField(default=dict)),
                ("output", models.JSONField(default=dict)),
                ("error_type", models.CharField(blank=True, default="", max_length=100)),
                ("error_message", models.CharField(blank=True, default="", max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("claim_token", models.UUIDField(blank=True, editable=False, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "workflow_orchestration_atom_execution",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ExecutionArtifact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("team", models.JSONField(default=list)),
                ("kind", models.CharField(choices=[("INSPECTION_REPORT", "巡检报告")], default="INSPECTION_REPORT", max_length=32)),
                ("format", models.CharField(choices=[("docx", "Word"), ("xlsx", "Excel")], max_length=8)),
                ("object_key", models.CharField(max_length=500, unique=True)),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=120)),
                ("sha256", models.CharField(max_length=64)),
                ("size", models.PositiveIntegerField()),
                ("summary", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "workflow_orchestration_execution_artifact",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="TriggerInvocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("team", models.JSONField(default=list)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "workflow_orchestration_trigger_invocation",
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("team", models.JSONField(default=list)),
                ("status", models.CharField(choices=[("DRAFT", "草稿"), ("PUBLISHED", "已发布")], default="DRAFT", max_length=16)),
                ("definition", models.JSONField(default=dict)),
                ("canvas_metadata", models.JSONField(default=dict)),
                ("trigger_types", models.JSONField(default=list)),
                ("engine_name", models.CharField(blank=True, max_length=100, unique=True)),
                ("current_version", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(db_index=True, default=False)),
                ("has_draft", models.BooleanField(db_index=True, default=True)),
                ("draft_revision", models.PositiveIntegerField(default=0)),
                ("draft_base_version", models.PositiveIntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deleted_by", models.CharField(blank=True, default="", max_length=32)),
                ("deleted_by_domain", models.CharField(blank=True, default="", max_length=100)),
            ],
            options={
                "db_table": "workflow_orchestration_workflow",
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("workflow_version", models.PositiveIntegerField()),
                ("conductor_workflow_id", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "排队中"),
                            ("RUNNING", "执行中"),
                            ("WAITING_APPROVAL", "等待审批"),
                            ("TERMINATING", "终止中"),
                            ("SUCCEEDED", "成功"),
                            ("FAILED", "失败"),
                            ("TIMED_OUT", "已超时"),
                            ("TERMINATED", "已终止"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=32,
                    ),
                ),
                ("team", models.JSONField(default=list)),
                ("input", models.JSONField(default=dict)),
                ("output", models.JSONField(default=dict)),
                ("has_warnings", models.BooleanField(default=False)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("tasks", models.JSONField(default=list)),
                ("definition_snapshot", models.JSONField(default=dict)),
                ("resource_snapshot", models.JSONField(default=dict)),
                ("target_snapshot", models.JSONField(default=dict)),
                ("launch_token_hash", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ("error_message", models.CharField(blank=True, default="", max_length=500)),
                ("failed_stage", models.CharField(blank=True, default="", max_length=32)),
                ("termination_reason", models.CharField(blank=True, default="", max_length=500)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("FORM", "表单"), ("SCHEDULE", "定时"), ("WEBHOOK", "API/Webhook"), ("NATS", "NATS")],
                        db_index=True,
                        default="FORM",
                        max_length=16,
                    ),
                ),
                ("trigger_id", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("mode", models.CharField(choices=[("PRODUCTION", "正式"), ("DEBUG", "调试")], db_index=True, default="PRODUCTION", max_length=16)),
                ("debug_kind", models.CharField(blank=True, choices=[("FULL", "全流程"), ("NODE", "单节点")], default="", max_length=16)),
                ("debug_task_reference", models.CharField(blank=True, default="", max_length=100)),
                ("started_by", models.CharField(db_index=True, default="", max_length=32)),
                ("domain", models.CharField(default="domain.com", max_length=100)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reruns",
                        to="workflow_orchestration.workflowexecution",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="executions", to="workflow_orchestration.workflow"),
                ),
            ],
            options={
                "db_table": "workflow_orchestration_execution",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WorkflowVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("version", models.PositiveIntegerField()),
                ("definition", models.JSONField(default=dict)),
                ("canvas_metadata", models.JSONField(default=dict)),
                ("resource_snapshot", models.JSONField(default=dict)),
                ("change_summary", models.JSONField(default=dict)),
                ("created_by", models.CharField(default="", max_length=32)),
                ("domain", models.CharField(default="domain.com", max_length=100)),
                (
                    "workflow",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="workflow_orchestration.workflow"),
                ),
            ],
            options={
                "db_table": "workflow_orchestration_version",
                "ordering": ("-version",),
            },
        ),
        migrations.CreateModel(
            name="WorkflowTrigger",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("node_key", models.CharField(blank=True, default="", max_length=100)),
                ("name", models.CharField(max_length=120)),
                (
                    "trigger_type",
                    models.CharField(choices=[("FORM", "表单"), ("SCHEDULE", "定时"), ("WEBHOOK", "API/Webhook"), ("NATS", "NATS")], max_length=16),
                ),
                ("enabled", models.BooleanField(db_index=True, default=False)),
                ("team", models.JSONField(default=list)),
                ("input_schema", models.JSONField(default=dict)),
                ("default_inputs", models.JSONField(default=dict)),
                ("config", models.JSONField(default=dict)),
                ("idempotency_window_seconds", models.PositiveIntegerField(default=3600)),
                ("next_run_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workflow",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="triggers", to="workflow_orchestration.workflow"),
                ),
            ],
            options={
                "db_table": "workflow_orchestration_trigger",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="WorkflowInteraction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("interaction_type", models.CharField(choices=[("APPROVAL", "审批")], max_length=24)),
                ("task_reference", models.CharField(db_index=True, max_length=100)),
                ("conductor_task_id", models.CharField(db_index=True, max_length=100)),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("candidate_users", models.JSONField(default=list)),
                ("public_context", models.JSONField(default=dict)),
                ("team", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "待处理"), ("APPROVED", "已通过"), ("REJECTED", "已拒绝"), ("TIMED_OUT", "已超时"), ("CANCELLED", "已取消")],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("operator", models.CharField(blank=True, default="", max_length=32)),
                ("operator_domain", models.CharField(blank=True, default="", max_length=100)),
                ("decision", models.CharField(blank=True, default="", max_length=16)),
                ("comment", models.CharField(blank=True, default="", max_length=500)),
                ("output", models.JSONField(default=dict)),
                ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("delivery_token", models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ("delivery_started_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_payload", models.JSONField(default=dict)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="interactions", to="workflow_orchestration.workflowexecution"
                    ),
                ),
            ],
            options={
                "db_table": "workflow_orchestration_interaction",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name", "team"), name="uq_workflow_active_name_team"
            ),
        ),
        migrations.AddField(
            model_name="triggerinvocation",
            name="execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trigger_invocations",
                to="workflow_orchestration.workflowexecution",
            ),
        ),
        migrations.AddField(
            model_name="triggerinvocation",
            name="trigger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invocations", to="workflow_orchestration.workflowtrigger"
            ),
        ),
        migrations.AddField(
            model_name="executionartifact",
            name="atom_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artifacts",
                to="workflow_orchestration.atomexecution",
            ),
        ),
        migrations.AddField(
            model_name="executionartifact",
            name="execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="workflow_orchestration.workflowexecution"
            ),
        ),
        migrations.AddField(
            model_name="atomexecution",
            name="execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="atom_executions", to="workflow_orchestration.workflowexecution"
            ),
        ),
        migrations.AddConstraint(
            model_name="atomdefinition",
            constraint=models.UniqueConstraint(fields=("name",), name="uq_workflow_atom_name"),
        ),
        migrations.AddConstraint(
            model_name="atomconfigtemplate",
            constraint=models.UniqueConstraint(fields=("organization_id", "atom_key", "name"), name="uq_workflow_atom_config_template_name"),
        ),
        migrations.AddConstraint(
            model_name="workflowversion",
            constraint=models.UniqueConstraint(fields=("workflow", "version"), name="uq_workflow_orchestration_version"),
        ),
        migrations.AddConstraint(
            model_name="workflowtrigger",
            constraint=models.UniqueConstraint(fields=("workflow", "name"), name="uq_workflow_trigger_name"),
        ),
        migrations.AddConstraint(
            model_name="workflowtrigger",
            constraint=models.UniqueConstraint(fields=("workflow", "node_key"), name="uq_workflow_trigger_node_key"),
        ),
        migrations.AddConstraint(
            model_name="workflowinteraction",
            constraint=models.UniqueConstraint(fields=("execution", "conductor_task_id"), name="uq_workflow_interaction_conductor_task"),
        ),
        migrations.AddConstraint(
            model_name="triggerinvocation",
            constraint=models.UniqueConstraint(fields=("trigger", "idempotency_key"), name="uq_workflow_trigger_idempotency"),
        ),
        migrations.AddConstraint(
            model_name="atomexecution",
            constraint=models.UniqueConstraint(fields=("execution", "task_reference", "attempt"), name="uq_workflow_atom_execution_attempt"),
        ),
    ]
